/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:65d7b9a6-0824-4f49-b11d-ce59f331a3b7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ST2mAaNxl",
    "aws_user_pools_web_client_id": "6gs3alck1cvv3nh33kl9k5d3sa",
    "oauth": {}
};


export default awsmobile;
